// Copyright (c) 2026 the go-widgets/desktop authors. All rights reserved.
//
// SPDX-License-Identifier: BSD-3-Clause

// Package source provides the two concrete shell.AppSource implementations that
// feed the desktop shell: the native xdgSource (source_xdg.go, !js), which
// scans a real XDG filesystem, and the embeddedSource (this file), which serves
// a curated app set, icon set and virtual file listing from an embed.FS. The
// embedded source is what makes the shell portable to the browser (js/wasm),
// where no real filesystem exists — the same shell/render composition renders a
// real, populated desktop with data baked into the binary.
package source

import (
	"embed"
	"strings"

	"github.com/go-freedesktop/desktopentry"
	"github.com/go-freedesktop/menu"
	"github.com/go-widgets/desktop/shell"
)

// assets holds the curated demo icons + thumbnails (generated by gen.go). Names
// are the bare icon-theme names (e.g. "web-browser.png") plus "thumb-*.png"
// previews for the virtual image files.
//
//go:embed assets/*.png
var assets embed.FS

// Embedded is the browser-facing shell.AppSource: a curated set of desktop
// entries, an application menu, a small virtual directory and the icons for all
// of them, served from an embed.FS with no filesystem access. It renders the
// identical shell/render composition the native xdgSource does.
type Embedded struct {
	apps *shell.AppIndex
	menu *shell.MenuModel
	dir  *shell.Dir

	icons  map[string][]byte // icon name / thumb key -> encoded PNG
	mimes  map[string]string // file extension -> MIME type
	assocs map[string][]shell.App
}

// compile-time assurance the embedded source satisfies the seam.
var _ shell.AppSource = (*Embedded)(nil)

// demoApp is one curated launchable app.
type demoApp struct {
	id, name, icon string
	cats           []string
}

// demoApps is the curated launchable set: a plausible modern Linux desktop,
// ordered arbitrarily (the AppIndex sorts by label).
var demoApps = []demoApp{
	{"org.gnome.TextEditor", "Text Editor", "accessories-text-editor", []string{"Utility", "TextEditor"}},
	{"org.mozilla.firefox", "Web Browser", "web-browser", []string{"Network", "WebBrowser"}},
	{"org.gnome.Nautilus", "Files", "system-file-manager", []string{"System", "FileManager"}},
	{"org.gnome.Console", "Terminal", "utilities-terminal", []string{"System", "TerminalEmulator"}},
	{"org.gnome.Calculator", "Calculator", "accessories-calculator", []string{"Utility", "Calculator"}},
	{"org.gnome.eog", "Image Viewer", "image-viewer", []string{"Graphics", "Viewer"}},
	{"org.gnome.Maps", "Maps", "maps", []string{"Utility", "Maps"}},
	{"org.videolan.VLC", "Media Player", "media-player", []string{"AudioVideo", "Player"}},
}

// menuCategory is one curated application-menu branch.
type menuCategory struct {
	name, dir string
	appIDs    []string
}

// demoMenu is the curated categorized menu (Freedesktop main categories).
var demoMenu = []menuCategory{
	{"Utility", "Accessories", []string{"org.gnome.TextEditor", "org.gnome.Calculator", "org.gnome.Maps"}},
	{"Network", "Internet", []string{"org.mozilla.firefox"}},
	{"System", "System Tools", []string{"org.gnome.Nautilus", "org.gnome.Console"}},
	{"Graphics", "Graphics", []string{"org.gnome.eog"}},
	{"AudioVideo", "Multimedia", []string{"org.videolan.VLC"}},
}

// demoFile is one entry of the virtual home directory.
type demoFile struct {
	name  string
	isDir bool
	mime  string
}

// demoFiles is the curated virtual directory shown in the file grid: two
// folders, a couple of documents and two image files (which get real
// thumbnails), so the grid is populated with a mix of icon and preview cells.
var demoFiles = []demoFile{
	{"Documents", true, shell.MimeDirectory},
	{"Pictures", true, shell.MimeDirectory},
	{"readme.txt", false, "text/plain"},
	{"notes.md", false, "text/plain"},
	{"budget.pdf", false, "application/pdf"},
	{"photo1.png", false, "image/png"},
	{"photo2.png", false, "image/png"},
	{"todo.txt", false, "text/plain"},
}

// NewEmbedded builds the curated, filesystem-free shell.AppSource.
func NewEmbedded() *Embedded {
	e := &Embedded{
		icons: map[string][]byte{},
		mimes: map[string]string{".txt": "text/plain", ".md": "text/plain", ".pdf": "application/pdf", ".png": "image/png"},
	}
	e.loadIcons()
	e.buildApps()
	e.buildMenu()
	e.buildDir()
	e.buildAssocs()
	return e
}

// loadIcons reads every embedded PNG into the icon map keyed by bare name.
func (e *Embedded) loadIcons() {
	ents, err := assets.ReadDir("assets")
	if err != nil {
		return
	}
	for _, ent := range ents {
		b, err := assets.ReadFile("assets/" + ent.Name())
		if err != nil {
			continue
		}
		e.icons[strings.TrimSuffix(ent.Name(), ".png")] = b
	}
}

// buildApps projects the curated set into an AppIndex through the same
// desktopentry -> shell.App path the native scan uses.
func (e *Embedded) buildApps() {
	entries := make([]*desktopentry.Entry, 0, len(demoApps))
	for _, a := range demoApps {
		entries = append(entries, entryFor(a))
	}
	e.apps = shell.NewAppIndex(entries)
}

// entryFor builds a desktop entry for a curated app (Exec is inert — "true" —
// since the browser cannot fork a process).
func entryFor(a demoApp) *desktopentry.Entry {
	return &desktopentry.Entry{
		ID:         a.id,
		Type:       "Application",
		Name:       a.name,
		Icon:       a.icon,
		Exec:       "true",
		Categories: a.cats,
	}
}

// buildMenu constructs the categorized menu tree and flattens it exactly as the
// native menu.Load path does.
func (e *Embedded) buildMenu() {
	byID := map[string]demoApp{}
	for _, a := range demoApps {
		byID[a.id] = a
	}
	root := &menu.Menu{Name: "Applications"}
	for _, c := range demoMenu {
		sub := &menu.Menu{Name: c.name, DirectoryName: c.dir}
		for _, id := range c.appIDs {
			if a, ok := byID[id]; ok {
				sub.Apps = append(sub.Apps, entryFor(a))
			}
		}
		root.Submenus = append(root.Submenus, sub)
	}
	e.menu = shell.NewMenuModel(&menu.Tree{Root: root})
}

// buildDir constructs the virtual directory listing, pre-classified.
func (e *Embedded) buildDir() {
	d := &shell.Dir{Path: "/home/user"}
	for _, f := range demoFiles {
		d.Items = append(d.Items, shell.FileItem{
			Name:  f.name,
			Path:  "/home/user/" + f.name,
			IsDir: f.isDir,
			Mime:  f.mime,
		})
	}
	e.dir = d
}

// buildAssocs wires a tiny "open with" table so Resolve returns real
// candidates (the browser cannot consult a mimeapps.list).
func (e *Embedded) buildAssocs() {
	all := e.apps.All()
	byID := map[string]shell.App{}
	for _, a := range all {
		byID[a.ID] = a
	}
	e.assocs = map[string][]shell.App{
		"text/plain":      {byID["org.gnome.TextEditor"]},
		"image/png":       {byID["org.gnome.eog"], byID["org.mozilla.firefox"]},
		"application/pdf": {byID["org.mozilla.firefox"]},
	}
}

// Apps returns the curated app index.
func (e *Embedded) Apps() *shell.AppIndex { return e.apps }

// Menu returns the curated application menu.
func (e *Embedded) Menu() *shell.MenuModel { return e.menu }

// Dir returns the virtual directory listing.
func (e *Embedded) Dir() *shell.Dir { return e.dir }

// Resolve classifies name by extension and returns its curated associations.
// content is unused (the embedded set carries no magic bytes), so this is a
// pure name-based classification — enough to drive the file grid + an
// "open with" menu in the browser.
func (e *Embedded) Resolve(name string, _ []byte) shell.OpenWith {
	mt := e.mimeByName(name)
	ow := shell.OpenWith{MimeType: mt}
	cands := e.assocs[mt]
	if len(cands) > 0 {
		ow.Default = cands[0]
		ow.HasDefault = true
		ow.Candidates = append(ow.Candidates, cands...)
	}
	return ow
}

// mimeByName maps a file name to a MIME type by extension (application/octet-
// stream when unknown).
func (e *Embedded) mimeByName(name string) string {
	i := strings.LastIndexByte(name, '.')
	if i < 0 {
		return "application/octet-stream"
	}
	if mt, ok := e.mimes[strings.ToLower(name[i:])]; ok {
		return mt
	}
	return "application/octet-stream"
}

// IconBytes resolves an icon name (or a "thumb-*" key) to its embedded PNG
// bytes, falling back through the mime name to a generic icon so a cell always
// gets a real image rather than a placeholder when a specific icon is absent.
func (e *Embedded) IconBytes(name string) ([]byte, bool) {
	if b, ok := e.icons[name]; ok {
		return b, true
	}
	// Per-MIME theme names (e.g. "text-plain", "image-png") fall back to the
	// shared generic icons the embed set actually carries.
	for _, fallback := range fallbacksFor(name) {
		if b, ok := e.icons[fallback]; ok {
			return b, true
		}
	}
	return nil, false
}

// fallbacksFor returns the ordered generic-icon candidates for a specific icon
// name that the embedded set may not carry verbatim.
func fallbacksFor(name string) []string {
	switch {
	case strings.HasPrefix(name, "image-"):
		return []string{"image-x-generic"}
	case strings.HasPrefix(name, "text-"):
		return []string{"text-x-generic"}
	case strings.HasPrefix(name, "application-"):
		return []string{"application-x-executable"}
	default:
		return []string{"application-x-executable"}
	}
}

// ThumbKey returns the embedded thumbnail asset key for an image file (mapping
// the two curated photos to their preview PNGs), or "" for anything else.
func (e *Embedded) ThumbKey(it shell.FileItem) string {
	if !shell.Thumbnailable(it) {
		return ""
	}
	switch it.Name {
	case "photo1.png":
		return "thumb-photo1"
	case "photo2.png":
		return "thumb-photo2"
	default:
		return ""
	}
}
